root_script: quarterly_metric_maker.sbat
Requirement already satisfied: decorator==5.1.0 in /home/casonk/.local/lib/python3.9/site-packages (5.1.0)
WARNING: You are using pip version 21.2.4; however, version 22.1 is available.
You should consider upgrading via the '/sw/arcts/centos7/python/3.9.7/bin/python3.9 -m pip install --upgrade pip' command.
Requirement already satisfied: networkx==2.6.3 in /home/casonk/.local/lib/python3.9/site-packages (2.6.3)
WARNING: You are using pip version 21.2.4; however, version 22.1 is available.
You should consider upgrading via the '/sw/arcts/centos7/python/3.9.7/bin/python3.9 -m pip install --upgrade pip' command.
Requirement already satisfied: pandas==1.3.5 in /home/casonk/.local/lib/python3.9/site-packages (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /home/casonk/.local/lib/python3.9/site-packages (from pandas==1.3.5) (1.22.3)
Requirement already satisfied: pytz>=2017.3 in /home/casonk/.local/lib/python3.9/site-packages (from pandas==1.3.5) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/casonk/.local/lib/python3.9/site-packages (from pandas==1.3.5) (2.8.2)
Requirement already satisfied: six>=1.5 in /sw/arcts/centos7/python/3.9.7/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas==1.3.5) (1.16.0)
WARNING: You are using pip version 21.2.4; however, version 22.1 is available.
You should consider upgrading via the '/sw/arcts/centos7/python/3.9.7/bin/python3.9 -m pip install --upgrade pip' command.
Requirement already satisfied: scipy==1.8.0 in /home/casonk/.local/lib/python3.9/site-packages (1.8.0)
Requirement already satisfied: numpy<1.25.0,>=1.17.3 in /home/casonk/.local/lib/python3.9/site-packages (from scipy==1.8.0) (1.22.3)
WARNING: You are using pip version 21.2.4; however, version 22.1 is available.
You should consider upgrading via the '/sw/arcts/centos7/python/3.9.7/bin/python3.9 -m pip install --upgrade pip' command.

/sw/arcts/centos7/python/3.9.7/bin/python

spinning up at: Fri May 20 00:47:31 EDT 2022
Job submitted by gl-login2.arc-ts.umich.edu
Job ID 36922046
Running on gl[3107-3111]
Running in /home/casonk/path/mmani_root/mmani0/shared_data/pushshift_python/Great_Lakes_HPC/pys 

Topics Defined 

Globals Defined 

Functions Defined 


truereddit.csv

Empty DataFrame
Columns: []
Index: []
Traceback (most recent call last):
  File "/home/casonk/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'off_topic'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/accounts/mmani_root/mmani0/shared_data/pushshift_python/Great_Lakes_HPC/pys/quarterly_metric_maker.py", line 325, in <module>
    meta_tricks(data, fname, 'conspiracy')
  File "/gpfs/accounts/mmani_root/mmani0/shared_data/pushshift_python/Great_Lakes_HPC/pys/quarterly_metric_maker.py", line 218, in meta_tricks
    off_mask = summary_tmp['off_topic'] >= _lambda * summary_tmp['on_topic']
  File "/home/casonk/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/casonk/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'off_topic'
backing up data to turbo buffer
/var/spool/slurmd.spool/job36922046/slurm_script: line 52: ./backup_quarterly_metricz_from_scratch.sh: Permission denied
spinning down at: Fri May 20 00:47:34 EDT 2022
