root_script: network_maker.sbat
Requirement already satisfied: decorator==5.0.9 in /home/casonk/.local/lib/python3.8/site-packages (5.0.9)
Requirement already satisfied: networkx==2.6.3 in /home/casonk/.local/lib/python3.8/site-packages (2.6.3)
Requirement already satisfied: pandas==1.3.5 in /home/casonk/.local/lib/python3.8/site-packages (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /sw/arcts/centos7/python3.8-anaconda/2021.05/lib/python3.8/site-packages (from pandas==1.3.5) (1.20.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /sw/arcts/centos7/python3.8-anaconda/2021.05/lib/python3.8/site-packages (from pandas==1.3.5) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /sw/arcts/centos7/python3.8-anaconda/2021.05/lib/python3.8/site-packages (from pandas==1.3.5) (2021.1)
Requirement already satisfied: six>=1.5 in /sw/arcts/centos7/python3.8-anaconda/2021.05/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas==1.3.5) (1.15.0)

/sw/arcts/centos7/python3.8-anaconda/2021.05/bin/python

spinning up at: Thu Mar 24 10:38:55 EDT 2022
Job submitted by gl-login1.arc-ts.umich.edu
Job ID 33998511
Running on gl3082
Running in /home/casonk/pushshift_python/Great_Lakes_HPC/sbats 

exception as : single positional indexer is out-of-bounds
backing up data to turbo buffer
source_csvz := /scratch/mmani_root/mmani0/shared_data/hot/csv_networkz/
target_csvz := /nfs/turbo/flnt-mmani/Reddit_Communities/buffer/csv_networkz/

0 files to copy

target_csvz directory purged

copying *.csv*
cp: cannot stat ‘/scratch/mmani_root/mmani0/shared_data/hot/csv_networkz/*.csv*’: No such file or directory

1 of 0 files copied

source_pklz := /scratch/mmani_root/mmani0/shared_data/hot/pkl_networkz/
target_pklz := /nfs/turbo/flnt-mmani/Reddit_Communities/buffer/pkl_networkz/

0 files to copy

target directory purged

copying *.pkl*
cp: cannot stat ‘/scratch/mmani_root/mmani0/shared_data/hot/pkl_networkz/*.pkl*’: No such file or directory

1 of 0 files copied

spinning down at: Thu Mar 24 11:11:54 EDT 2022
